# Generated by Django 3.1.7 on 2021-05-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(help_text='Введите наименование товара', max_length=30, unique=True, verbose_name='Наименование товара')),
                ('description', models.TextField(help_text='Введите описание товара', max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('discount', models.IntegerField(verbose_name='Скидка %')),
                ('brand', models.CharField(help_text='Введите бренд товара', max_length=30, verbose_name='Бренд')),
                ('color', models.CharField(help_text='Введите цвет товара', max_length=15, verbose_name='Цвет')),
                ('composition', models.CharField(help_text='Введите состав товара', max_length=50, verbose_name='Состав')),
                ('good_shifr', models.CharField(help_text='Введите артикул товара', max_length=12, unique=True, verbose_name='Артикул')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('category_name', models.CharField(help_text='Введите наименование категории', max_length=50, unique=True, verbose_name='Наименование категории')),
                ('seller_name', models.CharField(help_text='Введите наименование организации', max_length=50, unique=True, verbose_name='Наименование организации')),
            ],
            options={
                'db_table': 'good_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Введите наименование категории', max_length=50, unique=True, verbose_name='Наименование категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('picture', models.ImageField(blank=True, upload_to='users/', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField()),
                ('from_number', models.CharField(max_length=30)),
                ('to_number', models.CharField(max_length=30)),
                ('status_response', models.CharField(max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Введите наименование тега', max_length=20, unique=True, verbose_name='Наименование тега')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(help_text='Введите наименование организации', max_length=50, unique=True, verbose_name='Наименование организации')),
                ('mode', models.CharField(help_text='Введите форму организации', max_length=50, verbose_name='Форма организации')),
                ('inn', models.CharField(help_text='Введите ИНН организации', max_length=12, unique=True, verbose_name='ИНН организации')),
                ('boss_name', models.CharField(help_text='Введите ФИО руководителя', max_length=50, verbose_name='ФИО руководителя')),
                ('okpo', models.CharField(help_text='Введите ОКПО организации', max_length=8, unique=True, verbose_name='ОКПО организации')),
                ('ogrnip', models.CharField(help_text='Введите ОГРНИП организации', max_length=13, unique=True, verbose_name='ОГРНИП организации')),
                ('email', models.EmailField(help_text='Введите e-mail организации', max_length=50, unique=True, verbose_name='e-mail организации')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(help_text='Введите наименование товара', max_length=30, unique=True, verbose_name='Наименование товара')),
                ('description', models.TextField(help_text='Введите описание товара', max_length=255, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('discount', models.IntegerField(verbose_name='Скидка %')),
                ('brand', models.CharField(help_text='Введите бренд товара', max_length=30, verbose_name='Бренд')),
                ('color', models.CharField(help_text='Введите цвет товара', max_length=15, verbose_name='Цвет')),
                ('composition', models.CharField(help_text='Введите состав товара', max_length=50, verbose_name='Состав')),
                ('good_shifr', models.CharField(help_text='Введите артикул товара', max_length=12, unique=True, verbose_name='Артикул')),
                ('in_stock', models.PositiveIntegerField(verbose_name='Количество товара на складе')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('archive', models.BooleanField(default=False, verbose_name='В архиве')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.seller', verbose_name='Продавец')),
                ('tag', models.ManyToManyField(help_text='Добавьте теги для товара', to='main.Tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
