# Generated by Django 3.1.7 on 2021-03-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Введите наименование категории', max_length=50, verbose_name='Наименование категории')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(help_text='Введите наименование организации', max_length=50, verbose_name='Наименование организации')),
                ('mode', models.CharField(help_text='Введите форму организации', max_length=50, verbose_name='Форма организации')),
                ('INN', models.CharField(help_text='Введите ИНН организации', max_length=12, verbose_name='ИНН организации')),
                ('Boss_name', models.CharField(help_text='Введите ФИО руководителя', max_length=50, verbose_name='ФИО руководителя')),
                ('OKPO', models.CharField(help_text='Введите ОКПО организации', max_length=8, verbose_name='ОКПО организации')),
                ('OGRNIP', models.CharField(help_text='Введите ОГРНИП организации', max_length=13, verbose_name='ОГРНИП организации')),
                ('email', models.EmailField(help_text='Введите e-mail организации', max_length=50, verbose_name='e-mail организации')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Введите наименование тега', max_length=20, verbose_name='Наименование тега')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(help_text='Введите наименование товара', max_length=30, verbose_name='Наименование товара')),
                ('description', models.CharField(help_text='Введите описание товара', max_length=255, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('discount', models.IntegerField(verbose_name='Скидка %')),
                ('brand', models.CharField(help_text='Введите бренд товара', max_length=30, verbose_name='Бренд')),
                ('color', models.CharField(help_text='Введите цвет товара', max_length=15, verbose_name='Цвет')),
                ('good_shifr', models.CharField(help_text='Введите артикул товара', max_length=12, verbose_name='Артикул')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.seller')),
                ('tag', models.ManyToManyField(help_text='Добавьте теги для товара', to='main.Tag')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['good_name'],
            },
        ),
    ]
