# Generated by Django 3.1.7 on 2021-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='defautl', verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
