# Generated by Django 3.1.7 on 2021-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='composition',
            field=models.CharField(default='Состав', help_text='Введите состав товара', max_length=50, verbose_name='Состав'),
            preserve_default=False,
        ),
    ]
