# Generated by Django 3.1.7 on 2021-03-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_good_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя пользователя', max_length=30, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(help_text='Введите фамилию пользователя', max_length=30, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(help_text='Введите e-mail пользователя', max_length=50, verbose_name='E-mail пользователя')),
            ],
        ),
    ]
