# Generated by Django 3.1.7 on 2021-03-31 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
