# Generated by Django 3.1.7 on 2021-04-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Boss_name',
            new_name='boss_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='INN',
            new_name='inn',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='OGRNIP',
            new_name='ogrnip',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='OKPO',
            new_name='okpo',
        ),
    ]
