# Generated by Django 3.1.7 on 2021-04-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='in_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество товара на складе'),
            preserve_default=False,
        ),
    ]
