# Generated by Django 3.1.7 on 2021-04-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_good_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='slug',
        ),
    ]
