# Generated by Django 3.1.7 on 2021-04-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_good_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='good',
            name='slug',
        ),
        migrations.AddField(
            model_name='good',
            name='archive',
            field=models.BooleanField(default=True, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(help_text='Введите описание товара', max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='good',
            name='tag',
            field=models.ManyToManyField(help_text='Добавьте теги для товара', to='main.Tag', verbose_name='Тэги'),
        ),
    ]
