# Generated by Django 3.1.7 on 2021-05-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210427_2150'),
        ('main', '0017_auto_20210427_1337'),
    ]

    operations = [
    ]
